language: erlang

otp_release:
  - 17.4

env:
  - ELIXIR_VSN=1.0.3

sudo: false

before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VSN/Precompiled.zip
  - unzip -qq Precompiled.zip -d elixir

install:
  - export PATH=$PWD/elixir/bin:$PATH

script: mix test --trace
