version: '3.3'

services:
  postgres:
    image: postgres:10.6
    ports:
      - 5432:5432

    tty: true
    stdin_open: true
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statix_test
      POSTGRES_INITDB_ARGS: --auth-host=trust